update:
  fields:
    account:
      required: true
      example: "steve@apple.com"
      selector:
        config_entry:
          integration: "icloud"

play_sound:
  fields:
    account:
      required: true
      example: "steve@apple.com"
      selector:
        config_entry:
          integration: "icloud"
    device_name:
      required: true
      example: "stevesiphone"
      selector:
        device:
          filter:
            integration: "icloud"

display_message:
  fields:
    account:
      required: true
      example: "steve@apple.com"
      selector:
        config_entry:
          integration: "icloud"
    device_name:
      required: true
      example: "stevesiphone"
      selector:
        device:
          filter:
            integration: "icloud"
    message:
      required: true
      example: "Hey Steve !"
      selector:
        text:
    sound:
      selector:
        boolean:

lost_device:
  fields:
    account:
      required: true
      example: "steve@apple.com"
      selector:
        config_entry:
          integration: "icloud"
    device_name:
      required: true
      example: "stevesiphone"
      selector:
        device:
          filter:
            integration: "icloud"
    number:
      required: true
      example: "+33450020100"
      selector:
        text:
    message:
      required: true
      example: "Call me"
      selector:
        text:
